languages:
- cpp
- name: cpp
  production:
    include:
      - .*/src/.*\..*
    exclude:
      - .*/googletest/.*\.h
      - .*/googletest/.*\.cpp
      - .*/googletest/.*\.c
      - .*/googletest/.*\.cc
  test:
    include:
      - /tests/.*\.h
      - /tests/.*\.cpp
