languages:
- cpp
- name: cpp
  production:
    include:
      - .*/src/.*\.cpp
      - .*/src/.*\.h
      - .*/src/.*\.cc
    exclude:
      - .*/googletest/.*\.h
      - .*/googletest/.*\.cpp
      - .*/googletest/.*\.c
      - .*/googletest/.*\.cc
      - .*/tests/.*\.h
      - .*/tests/.*\.cpp
  test:
    include:
      - .*/tests/.*\.h
      - .*/tests/.*\.cpp
