component_depth: 1
languages:
- name: cpp
  production:
    include:
      - .*/src/.*\.cpp
      - .*/src/.*\.h
      - .*/src/.*\.cc
    exclude:
      - .*/tests/.*\.h
      - .*/tests/.*\.cpp
  test:
    include:
      - .*/tests/.*\.h
      - .*/tests/.*\.cpp
exclude:
- .*/googletest/.*
